### ISSUE TITLE
TOC Sidebar disappears with narrow window size

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-sphinx-theme#31]
On my screen, if I make the chrome window half screen (i.e. snap to the right side of my widescreen monitor), then the sidebar disappears.

My monitors are 1920 x 1080, so a window of ~960 x 1080 has no sidebar (I'm not sure how wide my vertical launcher task bar is on the monitor)

**Comment by tbekolay** [comment]
The sidebar disappearing is a feature to make the main content readable on small screens like phones. However, I believe what's supposed to happen is that the links in the sidebar move to the top or bottom of the page and that doesn't seem to be happening (or if it's happening it's not in an obvious way) so that's definitely a bug.

It's not something I'd want to spend too much time on given the impending redesign, but we should try to make a quick and dirty fix.

**Comment by drasmuss** [comment]
This is fixed in more recent versions of the theme (there's a little arrow that will pop out the sidebar).
