### ISSUE TITLE
Sphinx references have smaller font size

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-sphinx-theme#43]
Links created by sphinx references have a smaller font size than normal (compared to regular links or other text).

For example:
<img width="108" alt="sphinx" src="https://user-images.githubusercontent.com/1952220/67414600-c545d400-f599-11e9-9a02-f7da2dc91241.PNG">

**Comment by hunse** [comment]
This is because they're defined as "code". All code has a slightly smaller font size, whether it's a link or not. (This is done in the original `bootstrap` that I don't think we wrote; my guess is it's because the mono font often appears slightly larger when using the same font size.) Do we want to increase the font size of all code? Or just code links?

**Comment by hunse** [comment]
All code (unlinked and linked) bigger:
![Screenshot from 2020-04-14 10-07-43](https://user-images.githubusercontent.com/1952250/79234308-11cae780-7e38-11ea-9359-e84ba9d11337.png)

Just code links bigger:
![Screenshot from 2020-04-14 10-08-03](https://user-images.githubusercontent.com/1952250/79234327-18f1f580-7e38-11ea-9fbe-44a4be29a281.png)
